# Generated by Django 3.1.3 on 2020-12-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_pk', models.CharField(max_length=40)),
                ('wallet_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.IntegerField()),
                ('payment_currency', models.CharField(max_length=50)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletscanner.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='walletAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_wallet_pk', models.CharField(max_length=40)),
                ('add_wallet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletscanner.wallet')),
            ],
        ),
    ]
