# Generated by Django 3.1.3 on 2020-12-21 16:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='additional_country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='additional_full_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='additional_phone_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='additional_street_address1',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='additional_town_or_city',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
