# Generated by Django 3.1.3 on 2020-12-23 13:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_addresses', '0002_auto_20201221_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='additional_country',
            field=django_countries.fields.CountryField(default='IE', max_length=2),
        ),
    ]
