# Generated by Django 3.1.3 on 2020-12-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freescanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifiers',
            options={'verbose_name_plural': 'Identifiers'},
        ),
        migrations.RenameField(
            model_name='identifiers',
            old_name='identifier_id',
            new_name='identifier_contract',
        ),
        migrations.AlterField(
            model_name='identifiers',
            name='identifier_type',
            field=models.CharField(choices=[('', 'Select identifier type'), ('Contract', 'Contract'), ('TRC10', 'TRC10 Token'), ('TRC20', 'TRC20 Token'), ('Wallet', 'Wallet Address')], max_length=100),
        ),
    ]
