# Generated by Django 3.1.3 on 2020-12-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freescanner', '0002_auto_20201225_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiers',
            name='identifier_contract',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
