# Generated by Django 3.1.3 on 2020-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freescanner', '0003_auto_20201225_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiers',
            name='identifier_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
